### ISSUE TITLE
Read timeout for `erpione` cannot be configured

### ISSUE THREAD

**Issue by alisianoi** [gematik/erp-e2e-testsuite#5]
Starting since last week or so, it feels like the number of following responses when using `erpione` has increased:

```
ERROR: Error during request: HTTPSConnectionPool(host='erpps-test.dev.gematik.solutions', port=443): Read timed out. (read timeout=20)
```

Would it maybe be possible to make the read timeout configurable (i.e. from the command line or environment variable)?

**Comment by alexanderkaiser** [comment]
Hello @alisianoi 

I have also experienced the same issue. My assumption is, we have some bottlenecks (probably one of the many proxies sitting in-between). Currently the timeout is set by default to 20s which was mostly enough.

Would you necessarily need to configure the timeout yourself? Otherwise I would suggest to simply increase the default (let's say to 60s) and see how far we will get with that. 

From my perspective this approach would keep the CLI simpler

**Comment by alisianoi** [comment]
Sure, whatever you think would make most sense here! I would still prefer a configurable timeout but a larger default value is also great

**Comment by alexanderkaiser** [comment]
Hi @alisianoi 

can you give the version [0.4.1](https://hub.docker.com/layers/gematik1/erpione/0.4.1/images/sha256-d3b56024ad80412250fc214e7d4c7c87f29843352dcf5c52883cffe782c11d29?context=explore) a try to double check if that would work for your needs.

Basically there shouldn't be any noticeable changes compared to `0.4.0` except of:
- the default timeout is increased from 20s to 60s 
- you can now overwrite the default with the environment variable `ERPIONE_REQ_TIMEOUT`
   - keep in mind that this must be an integer value, so `export ERPIONE_REQ_TIMEOUT=60` would be fine, while `export ERPIONE_REQ_TIMEOUT=60.5` (or any other value which cannot be converted to an int) will yield in a `ValueError`

**Comment by alisianoi** [comment]
Thank you @alexanderkaiser, tried it with `0.4.2` and it worked for me
